=== andnovar/SmartSensorMobility/dist/resource/parameterable.dtd
<!ELEMENT rootcomposite (default?,parameterable*)>
<!ATTLIST rootcomposite
				name CDATA #REQUIRED
                file CDATA #IMPLIED
                lazyLoadableID CDATA #IMPLIED>
<!ELEMENT composite (default?,(parameterable*|parameter*|composite*))>
<!ATTLIST composite
				name CDATA #REQUIRED
				lazyReference CDATA #IMPLIED
				lazyLoadableID CDATA #IMPLIED
				import CDATA #IMPLIED>
<!ELEMENT parameterable (parameter|composite|parameterable)*>
<!ATTLIST parameterable
				name CDATA #REQUIRED
                class CDATA #REQUIRED>
<!ELEMENT default (parameter|composite|parameterable)*>
<!ELEMENT parameter EMPTY>
<!ATTLIST parameter
                name CDATA #REQUIRED
                value CDATA #REQUIRED
                class CDATA #IMPLIED>

=== andnovar/SmartSensorMobility/resource/combinerconfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE rootcomposite SYSTEM "resource/parameterable.dtd">
<rootcomposite >
<parameterable name="combiner" class="edu.sharif.ce.dml.mobisim.evaluator.model.EvaluationCombiner">
        <parameterable name="evaluationfiles" class="edu.sharif.ce.dml.common.parameters.logic.complex.MultipleSelectParameter">
            <parameter name="variablenumber" value="t"/>
            <composite name="selected" >
            </composite>
            <composite name="choices" >
				<parameterable name="EvaluationFiles"
                               class="edu.sharif.ce.dml.common.parameters.logic.parameterable.FileParameter">
                    <parameter name="fileaddress" value="output"/>
                    <parameter name="multiple" value="t"/>
                    <parameter name="defaultfilter"
                               value="edu.sharif.ce.dml.common.data.trace.filter.EvaluationFilter"/>
                </parameterable>
            </composite>
        </parameterable>
		        <parameterable name="outputfile"
                       class="edu.sharif.ce.dml.common.parameters.logic.complex.ParameterableParameter">
            <composite name="choice">
                <parameterable name="outputfile"
                               class="edu.sharif.ce.dml.common.parameters.logic.parameterable.FileParameter">
                    <parameter name="fileaddress" value="output"/>
                    <parameter name="multiple" value="f"/>
                    <parameter name="defaultfilter"
                               value="edu.sharif.ce.dml.common.data.trace.filter.EvaluationFilter"/>
                </parameterable>
            </composite>
        </parameterable>

    </parameterable>
</rootcomposite>

=== andnovar/SmartSensorMobility/dist/resource/tracewriter.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE rootcomposite SYSTEM "resource/parameterable.dtd">
<rootcomposite name="choice">
    <parameterable name="tracewriterconfig"
                   class="edu.sharif.ce.dml.common.data.trace.config.TraceWriterConfig">
        <parameterable name="outputfolder"
                       class="edu.sharif.ce.dml.common.parameters.logic.complex.ParameterableParameter">
            <composite name="choice">
                <parameterable name="outputfolder"
                               class="edu.sharif.ce.dml.common.parameters.logic.parameterable.FileParameter">
                    <parameter name="fileaddress" value="output"/>
                    <parameter name="multiple" value="f"/>
					<parameter name="isinput" value="f"/>
                    <parameter name="defaultfilter"
                               value="edu.sharif.ce.dml.common.data.trace.filter.DirectoryFilter"/>
                </parameterable>
            </composite>
        </parameterable>
        <parameterable name="tracewriter"
                       class="edu.sharif.ce.dml.common.parameters.logic.complex.SelectOneParameterable">
            <parameter name="selected" value="text"/>
            <composite name="choices">
                <parameterable name="text"
                               class="edu.sharif.ce.dml.common.data.trace.plaintext.TextTraceWriter"/>
                <parameterable name="xml" class="edu.sharif.ce.dml.common.data.trace.xml.XMLTraceWriter"/>
				<parameterable name="NS" class="edu.sharif.ce.dml.common.data.trace.ns.NSTraceWriter"/>
            </composite>
        </parameterable>
        <parameterable name="filenamegenerator"
                       class="edu.sharif.ce.dml.common.parameters.logic.complex.SelectOneParameterable">
            <parameter name="selected" value="simple"/>
            <composite name="choices">
                <parameterable name="simple"
                               class="edu.sharif.ce.dml.common.data.trace.filenamegenerator.SimpleFileName">
                    <parameter name="seed" value="outputtrace"/>
                    <parameter name="numberiterate" value="t"/>
                </parameterable>
            </composite>
        </parameterable>
    </parameterable>
</rootcomposite>

=== andnovar/SmartSensorMobility/resource/evaloatorsconfig.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE rootcomposite SYSTEM "resource/parameterable.dtd">
<rootcomposite name="">
    <default>
        <parameter name="sampletime" value="1"/>
		<parameter name="sortpriority" value="0"/>		
    </default>
    <parameterable name="1" class="edu.sharif.ce.dml.mobisim.evaluator.model.network.ConnectivityEvaluator">
    </parameterable>
    <parameterable name="2" class="edu.sharif.ce.dml.mobisim.evaluator.model.network.ConnectivityRatioEvaluator">
    </parameterable>
    <parameterable name="4" class="edu.sharif.ce.dml.mobisim.evaluator.model.network.AverageNodeDegree">
    </parameterable>
    <parameterable name="5" class="edu.sharif.ce.dml.mobisim.evaluator.model.network.NetworkDiameterEvaluator">
    </parameterable>
    <parameterable name="6" class="edu.sharif.ce.dml.mobisim.evaluator.model.network.AvarageRange">
    </parameterable>
	<parameterable name="8" class="edu.sharif.ce.dml.mobisim.evaluator.model.network.ClusteringCoefficient">
    </parameterable>
	<parameterable name="9" class="edu.sharif.ce.dml.mobisim.evaluator.model.network.LinkEvaluator2">
    </parameterable>
	<parameterable name="11" class="edu.sharif.ce.dml.mobisim.evaluator.model.network.Interference">
    </parameterable>	
	
	<parameterable name="14" class="edu.sharif.ce.dml.mobisim.evaluator.model.position.RelativeSpeedCalculator">
    </parameterable>
    <parameterable name="15" class="edu.sharif.ce.dml.mobisim.evaluator.model.position.SpatialCalculator">
        <parameter name="maxspatialrelation" value="100"/>
    </parameterable>
    <parameterable name="16" class="edu.sharif.ce.dml.mobisim.evaluator.model.position.TemporalCalculator">
        <parameter name="maxtimerelation" value="30"/>
    </parameterable>
    <parameterable name="17" class="edu.sharif.ce.dml.mobisim.evaluator.model.position.AverageDistance">
    </parameterable>
	<parameterable name="18" class="edu.sharif.ce.dml.mobisim.evaluator.model.position.LocationDistributionVariance">
		<parameter name="slicesize" value="20"/>
    </parameterable>
	<parameterable name="19" class="edu.sharif.ce.dml.mobisim.evaluator.model.position.RepetitiveBehavior">
		<parameter name="initialpointselectionsampletime" value="20"/>
		<parameter name="range" value="50"/>
    </parameterable>
	<parameterable name="20" class="edu.sharif.ce.dml.mobisim.evaluator.model.position.TransitionEvaluator">
		<parameter name="transitiondirectionthreshold" value="0"/>
		<parameter name="transitionspeedthreshold" value="3"/>
    </parameterable>
</rootcomposite>

=== andnovar/SmartSensorMobility/dist/resource/evaluatoranalyzerconfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE rootcomposite SYSTEM "resource/parameterable.dtd">
<rootcomposite >
    <default>
		<parameterable name="learnfile" class="edu.sharif.ce.dml.common.parameters.logic.complex.ParameterableParameter">
            <composite name="choice">
                <parameterable name="learnfile" class="edu.sharif.ce.dml.common.parameters.logic.parameterable.FileParameter">
                    <parameter name="fileaddress" value="1.txt"/>
                    <parameter name="multiple" value="f"/>
					<parameter name="isinput" value="t"/>
                    <parameter name="defaultfilter" value="edu.sharif.ce.dml.common.data.trace.filter.EvaluationFilter"/>
                </parameterable>
            </composite>
        </parameterable>
    </default>
    <parameterable name="Nearest Center Classification"
                   class="edu.sharif.ce.dml.mobisim.evaluationanalyzer.model.center.NearestCenter">        
    </parameterable>
	<parameterable name="Fuzzy KNN Classification"
                   class="edu.sharif.ce.dml.mobisim.evaluationanalyzer.model.fuzzy.FuzzyClassification">
		<parameter name="kneighbors" value="5"/>
		<parameter name="distanceweight" value="2"/>
    </parameterable>
	<parameterable name="Guassian KNC Classification"
                   class="edu.sharif.ce.dml.mobisim.evaluationanalyzer.model.center.GuassianKnc">
    </parameterable>
	<parameterable name="Guassian KNC2 Classification"
                   class="edu.sharif.ce.dml.mobisim.evaluationanalyzer.model.center.GuassianKnc2">
    </parameterable>
	<parameterable name="Guassian KNC3 Classification"
                   class="edu.sharif.ce.dml.mobisim.evaluationanalyzer.model.center.GuassianKnc3">
    </parameterable>
	<parameterable name="Nearest SVD Classification"
                   class="edu.sharif.ce.dml.mobisim.evaluationanalyzer.model.distance.NearestSVD">
    </parameterable>
	<parameterable name="Group SVD Classification"
                   class="edu.sharif.ce.dml.mobisim.evaluationanalyzer.model.distance.GroupSVD">
        <parameter name="singularcost" value="10"/>
    </parameterable>
	<parameterable name="Nearest Distance Classification"
                   class="edu.sharif.ce.dml.mobisim.evaluationanalyzer.model.distance.NearestDistance">
    </parameterable>
</rootcomposite>

=== andnovar/SmartSensorMobility/resource/locationinitializer.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE rootcomposite SYSTEM "resource/parameterable.dtd">
<rootcomposite name="">
    <parameterable name="random initializer"
	  class="edu.sharif.ce.dml.mobisim.mobilitygenerator.simulation.model.initiallocation.RandomSquareLocationInitializer">

		<parameterable name="random1"
		class="edu.sharif.ce.dml.common.parameters.logic.complex.ParameterableParameter">

		  <composite name="choice">
			<parameterable name="RandomValue"
			class="edu.sharif.ce.dml.common.parameters.logic.parameterable.random.RandomParameterable">

			  <parameter name="distribution"
			  value="Uniform" />
			  <parameter name="params" value="0,1" />
			  <parameter name="bias" value="0" />
			  <parameter name="scale" value="1" />
			</parameterable>
			
		  </composite>
		</parameterable>
		<parameterable name="random2"
		class="edu.sharif.ce.dml.common.parameters.logic.complex.ParameterableParameter">

		  <composite name="choice">
			<parameterable name="RandomValue"
			class="edu.sharif.ce.dml.common.parameters.logic.parameterable.random.RandomParameterable">

			  <parameter name="distribution" value="Uniform" />
			  <parameter name="params" value="0,1" />
			  <parameter name="bias" value="0" />
			  <parameter name="scale" value="1" />
			</parameterable>
		  </composite>
		</parameterable>
	  </parameterable>
	  <parameterable name="fixed initializer"
	  class="edu.sharif.ce.dml.mobisim.mobilitygenerator.simulation.model.initiallocation.FixedLocationInitializer">
		<parameterable name="locations"
  class="edu.sharif.ce.dml.common.parameters.logic.complex.MultipleSelectParameter">

			<parameter name="variablenumber" value="true" />
			<composite name="selected">
				<parameterable name="sampleLocation"
				  class="edu.sharif.ce.dml.common.parameters.logic.parameterable.LocationParameter">

					<parameter name="x" value="200.0" />
					<parameter name="y" value="200.0" />
				  </parameterable>
			</composite>
			<composite name="choices">
			  <parameterable name="defaultLocation"
			  class="edu.sharif.ce.dml.common.parameters.logic.parameterable.LocationParameter">

				<parameter name="x" value="200.0" />
				<parameter name="y" value="200.0" />
			  </parameterable>
			</composite>
		  </parameterable>
	  </parameterable>
</rootcomposite>
